apiVersion: v1
kind: Service
metadata:
  name: poc-wordpress-svc
  labels:
    app: poc-wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: poc-wordpress